# Lead Page WebElements

newButton = "xpath://a[@title='New']/self::a[@class='forceActionLink']"
lastNameInput = "xpath://input[@name='lastName']"
dbaNameInput = "xpath://input[@name='Company']"
phoneInput = "xpath://input[@name='Phone']"
mobileInput = "xpath://input[@name='MobilePhone']"
emailInput = "xpath://input[@name='Email']"
salesBranchLevel1 = "xpath://button[@name='Sales_Branch_Level_1_WF__c']"
sbL1PicklistValue = "xpath://span[@class='slds-truncate']/self::span[contains(text(),'Bags & Footwear & Accessories')]"
salesBranchLevel3 = "xpath://button[@name='Sales_Branch_Level_3_WF__c']"
sbL3PicklistValue = "xpath://span[@class='slds-truncate']/self::span[contains(text(),'Children footwear')]"
cityInput = "xpath://input[@name='city']"
postalCodeInput = "xpath://input[@name='postalCode']"
saveButton = "xpath://button[contains(text(),'Save')]/self::button[@class='slds-button slds-button_brand']"
leadLink = "xpath://a[@title='hDPpyakVzuWF']"
markAsCompleteButton = "xpath://span[@class='uiOutputText']/self::span[contains(text(),'Mark Status as Complete')]"
dcConvertButton = "xpath://button[@class='slds-button slds-button_neutral']/self::button[contains(text(),'DC Convert')]"
countryCode = "xpath://input[@name='country']"
countryCodePicklist = "xpath://span[@class='slds-truncate']/self::span[contains(text(),'Afghanistan')]"
footer = "xpath://div[@class='entityPanel slds-box_border expand slds-p-bottom_small']/following::footer[@class='slds-modal__footer']"
convertButton = "xpath://button[@class='slds-button slds-button_brand']/self::button[@title='Convert']"
cancelButton = "xpath://button[@title='Cancel']/self::button[@class='slds-button slds-button_neutral']"
