# New Opportunity Creation - Page objects

accountNavigationLink = "xpath://span[contains(text(),'Accounts')]/self::span[@class='slds-truncate']"
accountListViewDropDownIcon = "xpath://span[@part='boundary']/ancestor::button[@title='Select a List View: Accounts']"
allAccountListOption = "xpath://span[contains(text(),'All Accounts')]/self::span[@class=' virtualAutocompleteOptionText']"
customerAccountType = "xpath://span[contains(text(),'Customer')]/self::span[@title='Customer']"
accountNameSort = "xpath://*[contains(text(),'Account Name')]/self::span[@class='slds-truncate']"
accountName = "xpath://a[@title='#kimchi cosplay']"
relatedTab = "xpath://li[@title='Related']/self::li[@class='slds-tabs_default__item']"
newOpportunityButton = "xpath://*[contains(text(),'New')]/ancestor::li[@data-target-selection-name='sfdc:CustomButton.Opportunity.New_WF']"
iframeXpath = "xpath://iframe[@title='accessibility title']"
nextButton = "xpath://button[@class='slds-button slds-button--neutral slds-button slds-button_neutral next-button uiButton--default uiButton']"
centerNameInput = "xpath://input[@class='slds-lookup__search-input slds-input input uiInput uiInputText uiInput--default uiInput--input']/self::input[@id='831:0']"
centerNameOption = "xpath://a[contains(text(),'Century City')]"
useType = "xpath://button[@class='slds-button slds-button_neutral slds-picklist__label updateJustifyContent']"
useTypeListOption = "xpath://span[@class='slds-truncate']/self::span[contains(text(),'Food Court')]"
unitOrNewUnit = "xpath://input[@class='slds-input input uiInput uiInputText uiInput--default uiInput--input']/self::input[@id='1015:0']"
unitSelectRadioButton = "xpath://div[@class='slds-backdrop slds-backdrop_open cUnitProductLinkComponent_WF']/preceding::input[@id='3:471;a']"
saveAndExitButton = "xpath://button[contains(text(),'Save and Exit')]"
spaceDelieveryInput = "xpath://input[@id='input-15']"
newRCDdate = "xpath://input[@id='input-18']"
expirationDate = "xpath://input[@id='input-21']"
saveButton = "xpath://button[@class='slds-button slds-button_brand save-btn btn primary-btn']"
markStageAsCompleteButton = "xpath://span[text()='Mark Stage as Complete']"
editOpportunityButton = "xpath://button[text()='Edit Opportunity']"
inputProjectedSales = "xpath://section[@id='GI_whoSection']/descendant::input[@name='projectedSales']"
saveAsDraftButton = "xpath://button[text()='Save As Draft']"