name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Run unit tests'
    runs-on:   window-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run Tests'
        run: npm run test
        
      
      
